# Site settings
title: Tech and Junk
email: gregg@greggbolinger.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Gregg. I live in Wichita, KS with my wife, 
  3 kids, and a dog. I write software for a living and love 
  all things geeky and nerdy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gdboling.github.io" # the base hostname & protocol for your site
twitter_username: gdbolinger
github_username:  gdboling
paginate: 5

# Build settings
markdown: kramdown
